#!/bin/bash
umount "/home/lorenzo-zurini/RUNTIME/"
umount "/home/lorenzo-zurini/TEMP/[0]"
rm -r "/home/lorenzo-zurini/TEMP/[0]"
umount "/home/lorenzo-zurini/TEMP/[1]/pfx/drive_c/Program Files (x86)/Microsoft Games/Age of Empires II"
rm -r "/home/lorenzo-zurini/TEMP/[1]"
umount "/home/lorenzo-zurini/TEMP/[2]/pfx/drive_c/Program Files (x86)/Microsoft Games/Age of Empires II"
rm -r "/home/lorenzo-zurini/TEMP/[2]"
umount "/home/lorenzo-zurini/TEMP/[3]/pfx/drive_c/Program Files (x86)/Microsoft Games/Age of Empires II"
rm -r "/home/lorenzo-zurini/TEMP/[3]"
umount "/home/lorenzo-zurini/TEMP/[4]/pfx/drive_c/Program Files (x86)/Microsoft Games/Age of Empires II"
rm -r "/home/lorenzo-zurini/TEMP/[4]"
umount "/home/lorenzo-zurini/TEMP/[5]/pfx/drive_c/Program Files (x86)/Microsoft Games/Age of Empires II"
rm -r "/home/lorenzo-zurini/TEMP/[5]"
umount "/home/lorenzo-zurini/TEMP/[6]/pfx/drive_c/Program Files (x86)/Microsoft Games/Age of Empires II"
rm -r "/home/lorenzo-zurini/TEMP/[6]"
umount "/home/lorenzo-zurini/TEMP/[7]/pfx/drive_c/Program Files (x86)/Microsoft Games/Age of Empires II"
rm -r "/home/lorenzo-zurini/TEMP/[7]"
umount "/home/lorenzo-zurini/TEMP/[8]/pfx/drive_c/Program Files (x86)/Microsoft Games/Age of Empires II"
rm -r "/home/lorenzo-zurini/TEMP/[8]"
umount "/home/lorenzo-zurini/TEMP/[9]/pfx/drive_c/Program Files (x86)/Microsoft Games/Age of Empires II/Sound/midi"
rm -r "/home/lorenzo-zurini/TEMP/[9]"
umount "/home/lorenzo-zurini/TEMP/[10]/pfx/drive_c/Program Files (x86)/Microsoft Games/Age of Empires II/FLAC Soundtrack"
rm -r "/home/lorenzo-zurini/TEMP/[10]"
#umount "/home/lorenzo-zurini/TEMP/[11]/pfx/drive_c/Program Files (x86)/Microsoft Games/Age of Empires II/age2_x1/Music"
#rm -r "/home/lorenzo-zurini/TEMP/[11]"
#rm -r "/home/lorenzo-zurini/TEMP/[12]"
