#ifndef RUNNERWRAPPER_H
#define RUNNERWRAPPER_H

#include <string>
#include "nlohmann/json.hpp"

// ---------------------------------------------------------------------------
// RunnerWrapper — small node-native helpers for ROLE:"runner" nodes (path + availability). A runner node IS the
// runner: its EXEC declares the invocation (EXECUTABLE/ARGS/ENV/REMOVE_ENV + CONTENT_ROOT/PREFIX_GENERATE), its
// PLATFORM.GUEST the platforms it serves, and its PARENT content closure the build (VFS layers). There is no runner
// "variant" any more — different runners are different nodes. The install work lives in RunnerInstall.
// ---------------------------------------------------------------------------
namespace RunnerWrapper {

// The read-only DEFPREFIX a PREFIX_GENERATE runner builds once at install, inside its own LIBRARY bundle dir:
// <BundleDir>/__DEFPREFIX__/default. (Generated by RunnerInstall; mounted whole at the runtime root at launch.)
std::string DefPrefixDir(const std::string &BundleDir);

// Whether a runner's EXECUTABLE can actually run on this system, given its EXEC block. A build-mounted runner
// (EXECUTABLE resolves from its mounted build / contains a %VAR%) and a native passthrough (empty EXECUTABLE) are
// always available; a bare PATH command (wine / umu-run / snes9x) only if found on PATH. Gates runners out of the
// picker / launch resolver.
bool ExecutableAvailable(const nlohmann::ordered_json &Exec);

} // namespace RunnerWrapper

#endif // RUNNERWRAPPER_H
